#!/bin/bash
ws="echo -e '' | dmenu"
case $1 in
    move)  i3-msg move workspace $(eval $ws) ;;
    switch) i3-msg workspace $(eval $ws) ;;
    *) echo -e "Options\n\tmove - move the focused container to a workspace\n\tswitch - switch the current workspace to the input" ;;
esac
